using System.ComponentModel;


namespace MathGame
{
	internal struct OperationsEnum
	{
		public enum EnumOperationsMethod : int
		{
			Addition,
			Subtraction,
			Multiplication,
			Division,
			Power,
			PowerScratch,
			SquareRoot,
			SquareRootScratch,
			SquareRootBinaryScratch,
			CubeRoot,
			CubeRootScratch,
			Exponential,
			ExponentialScratch,
			LogarithmBase10,
			LogarithmBase10Scratch,
			Factorial,
			FactorialScratch,
			Logarithm,
			LogarithmScratch,
			LogarithmNatural,
			LogarithmNaturalScratch,
			AbsoluteValue,
			AbsoluteValueScratch,
			Modulus,
			ModulusScratch,
			Sin,
			SinScratch,
			Cos,
			CosScratch,
			Tan,
			TanScratch,
			Cot,
			CotScratch,
			Sec,
			SecScratch,
			Csc,
			CscScratch,
			
		}

		// unicode characters will be used to aviod issues and be able to use a variety of characters
		public enum EnumOperationMethodUnicodeSymbol
		{
			u002B,
			u002D,
			//u002A,
			u0078,
			u00F7,
			u1DBA,
			u221A,
			u221B,
			u212F,
			u33D2,
			u33D1,
			u2226,
			u006D,
			mod,
			sin,
			cos,
			tan,
			cot,
			sec,
			csc
			//+,
			//−,
			//×,
			//÷,
			//xⁿ,
			//√x,
			//³√x,
			//eˣ,
			//log10,
			//ln,
			//|x|,
			//mod,
			//sin,
			//cos,
			//tan,
			//cot,
			//sec,
			//csc


		}

		public enum EnumOperationsMethodUnitSymbol
		{
				[Description("+")] Addition,
				[Description("−")] Subtraction,
				[Description("×")] Multiplication,
				[Description("÷")] Division,
				[Description("^")] Power,
				[Description("^")] PowerScratch,
				[Description("xⁿ")] Exponentiation,
				[Description("√x")] SquareRoot,
				[Description("√x")] SquareRootScratch,
				[Description("√x")] SquareRootBinaryScratch,
				[Description("³√x")] CubeRoot,
				[Description("³√x")] CubeRootScratch,
				[Description("eˣ")] Exponential,
				[Description("eˣ")] ExponentialScratch,
				[Description("log10")] LogarithmBase10,
				[Description("log10")] LogarithmBase10Scratch,
				[Description("!")] Factorial,
				[Description("!")] FactorialScratch,
				[Description("ln")] NaturalLogarithm,
				[Description("ln")] NaturalLogarithmScratch,
				[Description("|x|")] AbsoluteValue,
				[Description("|x|")] AbsoluteValueScratch,
				[Description("mod")] Modulus,
				[Description("mod")] ModulusScratch,
				[Description("sin")] Sine,
				[Description("sin")] SineScratch,
				[Description("cos")] Cosine,
				[Description("cos")] CosineScratch,
				[Description("tan")] Tangent,
				[Description("tan")] TangentScratch,
				[Description("cot")] Cotangent,
				[Description("cot")] CotangentScratch,
				[Description("sec")] Secant,
				[Description("sec")] SecantScratch,
				[Description("csc")] Cosecant,
				[Description("csc")] CosecantScratch
			}


		public enum EnumOperationsMethodPrefix
		{
			A,
			B,
			C,
			D,
			E,
			F,
			G,
			H,
			I,
			J,
			K,
			L,
			M,
			N,
			O,
			P,
			Q,
			R,
			S,
			T,
			U,
			V,
			W,
			X,
			Y,
			Z,
			a,
			b,
			c,
			d,
			e,
			f,
			g,
			h,
			i,
			j,
			k,
			l,
			m,
			n,
			o,
			p,
			q,
			r,
		}
	}
}
