<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="Microsoft.TestPlatform" Version="17.14.0" />
    <PackageReference Include="Microsoft.VisualStudio.TestPlatform" Version="14.0.0" Alias="VSTestPlatform" />
    <PackageReference Include="Microsoft.VisualStudio.UnitTesting" Version="11.0.50727.1" Alias="VSUnitTesting" />
    <PackageReference Include="MSTest" Version="3.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MathCalculator\MathGame.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" Alias="VSTestTools" />
  </ItemGroup>
  

</Project>
